/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v12.0
processor: MIMXRT1062xxxxA
package_id: MIMXRT1062DVJ6A
mcu_data: ksdk2_0
processor_version: 12.0.0
external_user_signals: {}
pin_labels:
- {pin_num: F2, pin_signal: GPIO_EMC_04, label: CAN2_SW, identifier: CAN2_SW}
- {pin_num: G5, pin_signal: GPIO_EMC_05, label: CAN2_LED, identifier: CAN2_LED}
- {pin_num: H5, pin_signal: GPIO_EMC_06, label: RUN_CANCAT, identifier: RUN_CANCAT}
- {pin_num: H3, pin_signal: GPIO_EMC_08, label: RUN_CANT, identifier: RUN_CANT}
- {pin_num: D9, pin_signal: GPIO_B0_10, label: RUN_SOCKETCAN, identifier: RUN_SOCKETCAN}
- {pin_num: B11, pin_signal: GPIO_B1_01, label: RUN_TRUCKDEVIL, identifier: RUN_TRUCKDEVIL}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: RUN_SW5, identifier: RUN_SW5}
- {pin_num: A10, pin_signal: GPIO_B0_11, label: RUN_SW6, identifier: RUN_SW6}
- {pin_num: D7, pin_signal: GPIO_B0_00, label: RUN_SW7, identifier: RUN_SW7}
- {pin_num: E8, pin_signal: GPIO_B0_02, label: RUN_SW8, identifier: RUN_SW8}
- {pin_num: C14, pin_signal: GPIO_B1_14, label: PWR_LED, identifier: PWR_LED}
- {pin_num: B14, pin_signal: GPIO_B1_15, label: CAN3_LED, identifier: CAN3_LED}
- {pin_num: C10, pin_signal: GPIO_B0_12, label: CAN3_SW, identifier: CAN3_SW}
- {pin_num: J13, pin_signal: GPIO_AD_B1_11, label: CAN1_SW, identifier: CAN1_SW}
- {pin_num: L13, pin_signal: GPIO_AD_B1_10, label: CAN1_LED, identifier: CAN1_LED}
- {pin_num: D8, pin_signal: GPIO_B0_03, label: TEENSY_LED, identifier: TEENSY_LED}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: M13, peripheral: CAN1, signal: RX, pin_signal: GPIO_AD_B1_09}
  - {pin_num: H13, peripheral: CAN1, signal: TX, pin_signal: GPIO_AD_B1_08}
  - {pin_num: G11, peripheral: CAN2, signal: RX, pin_signal: GPIO_AD_B0_03}
  - {pin_num: M11, peripheral: CAN2, signal: TX, pin_signal: GPIO_AD_B0_02}
  - {pin_num: E4, peripheral: CAN3, signal: RX, pin_signal: GPIO_EMC_37}
  - {pin_num: C3, peripheral: CAN3, signal: TX, pin_signal: GPIO_EMC_36}
  - {pin_num: F2, peripheral: GPIO4, signal: 'gpio_io, 04', pin_signal: GPIO_EMC_04, direction: OUTPUT, gpio_init_state: 'false', speed: MHZ_200, slew_rate: Fast}
  - {pin_num: G5, peripheral: GPIO4, signal: 'gpio_io, 05', pin_signal: GPIO_EMC_05, direction: OUTPUT, gpio_init_state: 'false', software_input_on: Disable}
  - {pin_num: H5, peripheral: GPIO4, signal: 'gpio_io, 06', pin_signal: GPIO_EMC_06, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: H3, peripheral: GPIO4, signal: 'gpio_io, 08', pin_signal: GPIO_EMC_08, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: D9, peripheral: GPIO2, signal: 'gpio_io, 10', pin_signal: GPIO_B0_10, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: B11, peripheral: GPIO2, signal: 'gpio_io, 17', pin_signal: GPIO_B1_01, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: A11, peripheral: GPIO2, signal: 'gpio_io, 16', pin_signal: GPIO_B1_00, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: A10, peripheral: GPIO2, signal: 'gpio_io, 11', pin_signal: GPIO_B0_11, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: D7, peripheral: GPIO2, signal: 'gpio_io, 00', pin_signal: GPIO_B0_00, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: E8, peripheral: GPIO2, signal: 'gpio_io, 02', pin_signal: GPIO_B0_02, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge}
  - {pin_num: C14, peripheral: GPIO2, signal: 'gpio_io, 30', pin_signal: GPIO_B1_14, direction: OUTPUT}
  - {pin_num: B14, peripheral: GPIO2, signal: 'gpio_io, 31', pin_signal: GPIO_B1_15, direction: OUTPUT}
  - {pin_num: D5, peripheral: LPUART7, signal: RX, pin_signal: GPIO_EMC_32}
  - {pin_num: C5, peripheral: LPUART7, signal: TX, pin_signal: GPIO_EMC_31}
  - {pin_num: C10, peripheral: GPIO2, signal: 'gpio_io, 12', pin_signal: GPIO_B0_12, direction: OUTPUT, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: J13, peripheral: GPIO1, signal: 'gpio_io, 27', pin_signal: GPIO_AD_B1_11, direction: OUTPUT, speed: MHZ_200, slew_rate: Fast}
  - {pin_num: L13, peripheral: GPIO1, signal: 'gpio_io, 26', pin_signal: GPIO_AD_B1_10, direction: OUTPUT}
  - {pin_num: M8, peripheral: USB1, signal: usb_otg1_dn, pin_signal: USB_OTG1_DN}
  - {pin_num: N12, peripheral: USB1, signal: usb_otg1_chd_b, pin_signal: USB_OTG1_CHD_B}
  - {pin_num: L8, peripheral: USB1, signal: usb_otg1_dp, pin_signal: USB_OTG1_DP}
  - {pin_num: N6, peripheral: USB1, signal: usb_otg1_vbus, pin_signal: USB_OTG1_VBUS}
  - {pin_num: D8, peripheral: GPIO2, signal: 'gpio_io, 03', pin_signal: GPIO_B0_03, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of CAN1_LED on GPIO_AD_B1_10 (pin L13) */
  gpio_pin_config_t CAN1_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_10 (pin L13) */
  GPIO_PinInit(GPIO1, 26U, &CAN1_LED_config);

  /* GPIO configuration of CAN1_SW on GPIO_AD_B1_11 (pin J13) */
  gpio_pin_config_t CAN1_SW_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_11 (pin J13) */
  GPIO_PinInit(GPIO1, 27U, &CAN1_SW_config);

  /* GPIO configuration of RUN_SW7 on GPIO_B0_00 (pin D7) */
  gpio_pin_config_t RUN_SW7_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B0_00 (pin D7) */
  GPIO_PinInit(GPIO2, 0U, &RUN_SW7_config);
  /* Enable GPIO pin interrupt on GPIO_B0_00 (pin D7) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 0U);

  /* GPIO configuration of RUN_SW8 on GPIO_B0_02 (pin E8) */
  gpio_pin_config_t RUN_SW8_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B0_02 (pin E8) */
  GPIO_PinInit(GPIO2, 2U, &RUN_SW8_config);
  /* Enable GPIO pin interrupt on GPIO_B0_02 (pin E8) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 2U);

  /* GPIO configuration of TEENSY_LED on GPIO_B0_03 (pin D8) */
  gpio_pin_config_t TEENSY_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_03 (pin D8) */
  GPIO_PinInit(GPIO2, 3U, &TEENSY_LED_config);

  /* GPIO configuration of RUN_SOCKETCAN on GPIO_B0_10 (pin D9) */
  gpio_pin_config_t RUN_SOCKETCAN_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B0_10 (pin D9) */
  GPIO_PinInit(GPIO2, 10U, &RUN_SOCKETCAN_config);
  /* Enable GPIO pin interrupt on GPIO_B0_10 (pin D9) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 10U);

  /* GPIO configuration of RUN_SW6 on GPIO_B0_11 (pin A10) */
  gpio_pin_config_t RUN_SW6_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B0_11 (pin A10) */
  GPIO_PinInit(GPIO2, 11U, &RUN_SW6_config);
  /* Enable GPIO pin interrupt on GPIO_B0_11 (pin A10) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 11U);

  /* GPIO configuration of CAN3_SW on GPIO_B0_12 (pin C10) */
  gpio_pin_config_t CAN3_SW_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B0_12 (pin C10) */
  GPIO_PinInit(GPIO2, 12U, &CAN3_SW_config);

  /* GPIO configuration of RUN_SW5 on GPIO_B1_00 (pin A11) */
  gpio_pin_config_t RUN_SW5_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B1_00 (pin A11) */
  GPIO_PinInit(GPIO2, 16U, &RUN_SW5_config);
  /* Enable GPIO pin interrupt on GPIO_B1_00 (pin A11) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 16U);

  /* GPIO configuration of RUN_TRUCKDEVIL on GPIO_B1_01 (pin B11) */
  gpio_pin_config_t RUN_TRUCKDEVIL_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_B1_01 (pin B11) */
  GPIO_PinInit(GPIO2, 17U, &RUN_TRUCKDEVIL_config);
  /* Enable GPIO pin interrupt on GPIO_B1_01 (pin B11) */
  GPIO_PortEnableInterrupts(GPIO2, 1U << 17U);

  /* GPIO configuration of PWR_LED on GPIO_B1_14 (pin C14) */
  gpio_pin_config_t PWR_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_14 (pin C14) */
  GPIO_PinInit(GPIO2, 30U, &PWR_LED_config);

  /* GPIO configuration of CAN3_LED on GPIO_B1_15 (pin B14) */
  gpio_pin_config_t CAN3_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_15 (pin B14) */
  GPIO_PinInit(GPIO2, 31U, &CAN3_LED_config);

  /* GPIO configuration of CAN2_SW on GPIO_EMC_04 (pin F2) */
  gpio_pin_config_t CAN2_SW_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_04 (pin F2) */
  GPIO_PinInit(GPIO4, 4U, &CAN2_SW_config);

  /* GPIO configuration of CAN2_LED on GPIO_EMC_05 (pin G5) */
  gpio_pin_config_t CAN2_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_05 (pin G5) */
  GPIO_PinInit(GPIO4, 5U, &CAN2_LED_config);

  /* GPIO configuration of RUN_CANCAT on GPIO_EMC_06 (pin H5) */
  gpio_pin_config_t RUN_CANCAT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_EMC_06 (pin H5) */
  GPIO_PinInit(GPIO4, 6U, &RUN_CANCAT_config);
  /* Enable GPIO pin interrupt on GPIO_EMC_06 (pin H5) */
  GPIO_PortEnableInterrupts(GPIO4, 1U << 6U);

  /* GPIO configuration of RUN_CANT on GPIO_EMC_08 (pin H3) */
  gpio_pin_config_t RUN_CANT_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_EMC_08 (pin H3) */
  GPIO_PinInit(GPIO4, 8U, &RUN_CANT_config);
  /* Enable GPIO pin interrupt on GPIO_EMC_08 (pin H3) */
  GPIO_PortEnableInterrupts(GPIO4, 1U << 8U);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_FLEXCAN2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_FLEXCAN2_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_FLEXCAN1_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_09_FLEXCAN1_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_GPIO1_IO26, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_00_GPIO2_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_02_GPIO2_IO02, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_03_GPIO2_IO03, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_10_GPIO2_IO10, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_11_GPIO2_IO11, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B0_12_GPIO2_IO12, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_GPIO2_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_01_GPIO2_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_14_GPIO2_IO30, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_15_GPIO2_IO31, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_04_GPIO4_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_05_GPIO4_IO05, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_06_GPIO4_IO06, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_08_GPIO4_IO08, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_31_LPUART7_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_32_LPUART7_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_36_FLEXCAN3_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_37_FLEXCAN3_RX, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR29 = ((IOMUXC_GPR->GPR29 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL(0x00U) 
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_11_GPIO1_IO27, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_B0_12_GPIO2_IO12, 0x10F1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_EMC_04_GPIO4_IO04, 0x10F1U); 
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
