#ifndef __LED_H__
#define __LED_H__

#include "pin_mux.h"
#include "fsl_gpio.h"

#define PWR_LED_On BOARD_INITPINS_PWR_LED_PORT->DR |= BOARD_INITPINS_PWR_LED_PIN_MASK
#define PWR_LED_Off BOARD_INITPINS_PWR_LED_PORT->DR &= ~(BOARD_INITPINS_PWR_LED_PIN_MASK)
void PWR_LED_Toggle();

#define CAN1_LED_On BOARD_INITPINS_CAN1_LED_PORT->DR |= BOARD_INITPINS_CAN1_LED_PIN_MASK
#define CAN1_LED_Off BOARD_INITPINS_CAN1_LED_PORT->DR &= ~(BOARD_INITPINS_CAN1_LED_PIN_MASK)
void CAN1_LED_Toggle();

#define CAN2_LED_On BOARD_INITPINS_CAN2_LED_PORT->DR |= BOARD_INITPINS_CAN2_LED_PIN_MASK
#define CAN2_LED_Off BOARD_INITPINS_CAN2_LED_PORT->DR &= ~(BOARD_INITPINS_CAN2_LED_PIN_MASK)
void CAN2_LED_Toggle();

#define CAN3_LED_On BOARD_INITPINS_CAN3_LED_PORT->DR |= BOARD_INITPINS_CAN3_LED_PIN_MASK
#define CAN3_LED_Off BOARD_INITPINS_CAN3_LED_PORT->DR &= ~(BOARD_INITPINS_CAN3_LED_PIN_MASK)
void CAN3_LED_Toggle();

#endif
