#ifndef __LED_H__
#define __LED_H__

#include "pin_mux.h"

#define PWR_LED_On GPIO_PinWrite(BOARD_INITPINS_PWR_LED_PORT, BOARD_INITPINS_PWR_LED_PIN, 1);
#define PWR_LED_Off GPIO_PinWrite(BOARD_INITPINS_PWR_LED_PORT, BOARD_INITPINS_PWR_LED_PIN, 0);

#define CAN1_LED_On GPIO_PinWrite(BOARD_INITPINS_CAN1_LED_PORT, BOARD_INITPINS_CAN1_LED_PIN, 1);
#define CAN1_LED_Off GPIO_PinWrite(BOARD_INITPINS_CAN1_LED_PORT, BOARD_INITPINS_CAN1_LED_PIN, 0);

#define CAN2_LED_On GPIO_PinWrite(BOARD_INITPINS_CAN2_LED_PORT, BOARD_INITPINS_CAN2_LED_PIN, 1);
#define CAN2_LED_Off GPIO_PinWrite(BOARD_INITPINS_CAN2_LED_PORT, BOARD_INITPINS_CAN2_LED_PIN, 0);

#define CAN3_LED_On GPIO_PinWrite(BOARD_INITPINS_CAN3_LED_PORT, BOARD_INITPINS_CAN3_LED_PIN, 1);
#define CAN3_LED_Off GPIO_PinWrite(BOARD_INITPINS_CAN3_LED_PORT, BOARD_INITPINS_CAN3_LED_PIN, 0);

#endif
