/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef __USB_DEVICE_INTERFACE_0_CIC_VCOM_H__
#define __USB_DEVICE_INTERFACE_0_CIC_VCOM_H__

/*******************************************************************************
 * Definitions
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif
/*!
 * @brief Interface task function.
 */
void USB_DeviceInterface0CicVcomTask(void);

#if defined(__cplusplus)
}
#endif
#endif /* __USB_DEVICE_INTERFACE_0_CIC_VCOM_H__ */
